FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Expõe a porta que o Uvicorn vai escutar
EXPOSE 8000

# Comando para iniciar a app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
